---
title: "ESM 262 Assignment 6"
author: "Sarah Hamilton"
date: "3/2/2022"
output: html_document
---

Code to test extreme temperature risk function

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
```

```{r}
#source the function
source("~/Desktop/Bren Winter 2022/ESM 262/esm262-assignments-hamilton/R/temp_risk_score.R")

#read in the temperature data, make it a data frame, make the first row the column names
daily_temp <- read.table(file = "~/Desktop/Bren Winter 2022/ESM 262/esm262-assignments-hamilton/data/tmax.txt") %>%
  as.data.frame() %>%
  janitor::row_to_names(row_number = 1)

#extract vector of temperatures
temp_vec <- as.double(daily_temp$tmax)

#run risk function on temperature vector
temp_results <- temp_risk_score(temp_vec, age = 50, temp_ideal = 25) #default values: age = 150, temp_ideal = 20, highest_threshold = 38, medium_threshold = 32
```

**Function Results for Risk of Heat to Pine Trees**
Risk Level: `r temp_results[1]`
Number of High Extreme Temperatures: `r temp_results[2]`
Number of Moderate Extreme Temperatures: `r temp_results[3]`
