---
title: 'ESM 244 Assignment 5: Fish'
author: "Sarah Hamilton"
date: "3/1/2022"
output: html_document
---

Demonstration of `fish_function()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
```

```{r}
source("~/Desktop/Bren Winter 2022/ESM 262/esm262-assignments-hamilton/R/fish_function.R")

fish_names <- read.table(file = "~/Desktop/Bren Winter 2022/ESM 262/esm262-assignments-hamilton/fish.txt", skip = 1)

fish_names$V1 <- as.factor(fish_names$V1)
fish_stats <- fish_function(fish_names$V1)
fish_stats
  
```

Challenge: Run summary function for if we had multiple catches (IN PROGRESS)

```{r}
# generate some data if we had 10 different fishing days
# some examples of using the purr family of functions
possible.fish = c("salmon","steelhead","shark","tuna","cod")

# lets generate random sample of the number of fish caught on each day
ndays=10
catches = round(runif(min=3, max=400, n=ndays))

# now for each fishing day (and its number of fish caught) - use sample to generate the fish
catches_res = list(catches) %>% pmap(sample, x=possible.fish, replace=TRUE)
# look at the sample catches
```

